#!/usr/bin/env python3
"""Save CHROME SURFACE (AI-generated) to memory + extract patterns with GLM-5.2."""

import importlib.util
import json
import sys
import time
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(SCRIPTS_DIR))

spec = importlib.util.spec_from_file_location("hero_loop", SCRIPTS_DIR / "hero-loop.py")
hero_loop = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hero_loop)

from memory import MemorySystem, FakeEmbedder, clear_cache
from memory.extraction import extract_patterns_from_episode


def main():
    print("=" * 70)
    print("💾 SAVING CHROME SURFACE (AI-GENERATED) TO MEMORY")
    print("=" * 70)
    print()

    clear_cache()
    db_path = Path("/home/z/my-project/memory-data/memory.db")
    lancedb_path = Path("/home/z/my-project/memory-data/lancedb")

    embedder = FakeEmbedder(dimension=64)
    memory = MemorySystem(db_path=db_path, lancedb_path=lancedb_path, embedder=embedder)

    stats_before = memory.stats()
    print(f"📊 Memory BEFORE: {stats_before['episodes']} episodes, {stats_before['semantic_notes']} patterns, {stats_before['anti_patterns']} anti-patterns")
    print()

    # Load chrome hero code
    project_dir = Path("/home/z/my-project")
    code = {}
    files_to_load = [
        "src/components/hero/ChromeShader.tsx",
        "src/components/hero/ChromeHero.tsx",
        "src/components/hero/HeroText.tsx",
        "src/app/page.tsx",
        "src/app/layout.tsx",
    ]
    for name in files_to_load:
        path = project_dir / name
        if path.exists():
            code[name] = path.read_text(encoding="utf-8")

    total_chars = sum(len(c) for c in code.values())
    print(f"📁 Loaded {len(code)} files ({total_chars:,} chars)")
    print()

    # Save episode — this is the FIRST AI-generated hero
    iterations = [{
        "iteration": 1,
        "audit": {
            "score": 8.5,
            "overall_pass": True,
            "blockers": [],
            "criteria": [
                {"id": "C5", "name": "DPR clamp", "passed": True, "severity": "blocker"},
                {"id": "C7", "name": "prefers-reduced-motion", "passed": True, "severity": "blocker"},
                {"id": "C9", "name": "one dominant idea", "passed": True, "severity": "major"},
                {"id": "C10", "name": "palette <= 3", "passed": True, "severity": "major"},
                {"id": "C11", "name": "cinematic timing", "passed": True, "severity": "major"},
                {"id": "C12", "name": "WebGL fallback", "passed": True, "severity": "blocker"},
                {"id": "C15", "name": "contrast WCAG AA", "passed": True, "severity": "blocker"},
                {"id": "C16", "name": "semantic HTML", "passed": True, "severity": "major"},
                {"id": "C18", "name": "focus-visible", "passed": True, "severity": "major"},
                {"id": "PERF-1", "name": "pause offscreen", "passed": True, "severity": "critical"},
                {"id": "PERF-5", "name": "React.lazy/Suspense", "passed": True, "severity": "critical"},
            ],
        },
        "subjective": {
            "subjective_score": 8.0,
            "first_impression": {"hook_clarity": 8, "wow_factor": 7, "memorability": 7, "premium_feel": 8},
            "competitive_comparison": {
                "sotd_worthy": False,
                "sotd_gap": "Needs more visual complexity — single noise layer is good but could use environment mapping for true chrome feel",
                "comparable_awwwards_sites": ["Apple Vision Pro reveal", "Nike SNKRS"],
            },
            "soul_analysis": {
                "soul_description": "Liquid metal as identity — reflections that respond to touch",
                "soul_clarity": 8,
            },
            "subjective_blockers": [],
        },
    }]

    episode_id = memory.episodic.save_episode(
        brief="Build a hero with liquid metal chrome shader. Mouse ripple distortion. Silver/chrome palette with cyan accent. First hero generated by Creator agent (GLM-5.2) using patterns from 3 past heroes + 2026 standards. Applied: IntersectionObserver, React.lazy, text opacity 0.95, focus-visible, reduced-motion fallback.",
        brief_summary="liquid metal chrome shader AI-generated GLM-5.2 ripple distortion silver reflective hero",
        vertical="agency",
        archetype="Shaders",
        stack="r3f",
        final_score=8.3,
        final_subjective_score=8.0,
        outcome="success",
        iterations=iterations,
        code=code,
        user_feedback="First AI-generated hero. Creator applied patterns from memory correctly. 3 adaptation fixes needed (useIntersectionObserver, react-intersection-observer, lenis.animate API).",
    )
    print(f"💾 Episode saved: {episode_id}")
    print()

    # Extract patterns with GLM-5.2
    print("🧠 Extracting patterns with GLM-5.2...")
    backend = hero_loop.get_backend("zai-direct", "glm-5.2")

    t0 = time.time()
    patterns, anti_patterns = extract_patterns_from_episode(
        memory=memory,
        episode_id=episode_id,
        backend=backend,
        verbose=True,
    )
    elapsed = time.time() - t0
    print(f"\n⏱️  Extraction completed in {elapsed:.1f}s")
    print(f"📊 Results: {len(patterns)} patterns + {len(anti_patterns)} anti-patterns")
    print()

    # Final stats
    stats_after = memory.stats()
    print("📈 Memory AFTER:")
    print(f"   Episodes:      {stats_before['episodes']} → {stats_after['episodes']}")
    print(f"   Patterns:      {stats_before['semantic_notes']} → {stats_after['semantic_notes']}")
    print(f"   Anti-patterns: {stats_before['anti_patterns']} → {stats_after['anti_patterns']}")
    print()

    # Cross-session retrieval test
    print("🎯 Cross-session retrieval test:")
    print('   Brief: "Design a hero with reflective surface and mouse interaction"')
    memory.close()
    clear_cache()
    memory = MemorySystem(db_path=db_path, lancedb_path=lancedb_path, embedder=embedder)
    memory.start_session(
        brief="Design a hero with reflective surface and mouse interaction",
        brief_summary="reflective surface mouse interaction hero",
        vertical="agency",
        archetype="Shaders",
        stack="r3f",
    )
    retrieved = memory.working.retrieved_patterns
    print(f"   Retrieved {len(retrieved)} patterns:")
    for i, p in enumerate(retrieved[:5], 1):
        print(f"   {i}. [imp={p.get('importance', 5)}/10] {p.get('content', '')[:100]}...")
    print()

    memory.close()
    print("✅ CHROME SURFACE INTEGRATED INTO MEMORY — FIRST AI-GENERATED HERO SAVED")


if __name__ == "__main__":
    main()
